"""Regression test for a real production failure (product owner, 2026-09-05):

    Publishing the very first hotel ever built with more than one brand-new room at once
    (HRG-H1 - Steigenberger Golf Resort El Gouna, 3 rooms: Deluxe Room / Premium Room / Junior
    Suite, none of them existing yet) failed with:

        {'error': 400, 'message': '{"error":["Room null already exists for contract
        HRG-H1"],"status":"BAD_REQUEST"}'}

    and the app's own error guidance told the human to "check the Tour/Ticket Code - choose a
    different one" - nonsensical for a Hotel publish, which has no such field.

Root cause: a room's providerCode is system-generated by Travel Compositor and only comes back
in the create/update response (see ContractRoomVO's own docstring in schemas.py) - so every
brand-new room in the outgoing payload carries providerCode=None. build_hotel_contract_payload's
main create_hotel()/update_hotel() call used to send the WHOLE rooms[] array (every brand-new
room, all with providerCode=None) in one shot. Every previously-confirmed real example (CAI-H1,
Four Seasons Cairo) only ever had ONE brand-new room at a time, so this never surfaced - Travel
Compositor's backend apparently can't tell two simultaneously-null room entries in the same
payload apart and rejects the second as already existing.

Fix: the main create_hotel()/update_hotel() call now submits AT MOST one brand-new room inline
(plus every room that already has a real providerCode, i.e. existing rooms being preserved on an
update) - any additional brand-new rooms are added afterward ONE AT A TIME via the existing (but
previously unused) POST /hotel/room endpoint (client.create_hotel_room), with each response
merged into the same room list resolve_room_provider_codes reads for phase 2. Separately, the
"already exists" error-guidance pattern was given a more specific, earlier-matching entry for
this exact room-conflict message, so a human seeing it (if it recurs, e.g. a genuine room-name
collision) gets guidance about the Rooms section, not a made-up Tour/Ticket Code field.

app.py can't be imported in a test process (heavy top-level Streamlit/API-client setup), so this
is verified by reading its own source text, per this suite's established pattern (see
test_2026_09_03_ticket_modality_code_slash_fix_and_batch_recovery.py) for testing app.py-only
functions/logic.
"""
import os

_APP_PY = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "app.py")


def _read_app_py():
    with open(_APP_PY, "r", encoding="utf-8") as f:
        return f.read()


# ======================================================================
# The room-splitting fix itself
# ======================================================================
def test_only_one_brand_new_room_is_sent_inline_on_the_main_create_or_update_call():
    src = _read_app_py()
    assert 'new_rooms = [r for r in all_rooms if not r.get("providerCode")]' in src
    assert 'extra_new_rooms = new_rooms[1:]' in src
    assert 'phase1_payload["rooms"] = rooms_with_code + new_rooms[:1]' in src


def test_existing_rooms_with_a_real_provider_code_are_still_sent_inline():
    """An update must still preserve already-published rooms in the same main call - only
    genuinely NEW (providerCode still None) rooms beyond the first get split out."""
    src = _read_app_py()
    assert 'rooms_with_code = [r for r in all_rooms if r.get("providerCode")]' in src


def test_extra_new_rooms_are_added_one_at_a_time_via_the_per_room_endpoint():
    src = _read_app_py()
    idx = src.index("extra_new_rooms = new_rooms[1:]")
    window = src[idx:idx + 5000]
    assert "for room_payload in extra_new_rooms:" in window
    assert "client.create_hotel_room(supplier_id, provider_code, room_payload)" in window


def test_room_add_failures_are_surfaced_not_silently_swallowed():
    src = _read_app_py()
    idx = src.index("extra_new_rooms = new_rooms[1:]")
    window = src[idx:idx + 5000]
    assert "room_add_failures" in window
    assert 'progress.error(f"⚠️ Couldn\'t add room' in window


def test_phase_2_room_map_is_built_from_every_room_response_merged_together():
    """The main call's response plus every create_hotel_room response must all feed into the
    same {room_name: providerCode} map phase 2 (offers/supplements/rates) reads - otherwise a
    room added via the per-room endpoint would silently have no prices/offers reach it."""
    src = _read_app_py()
    idx = src.index("extra_new_rooms = new_rooms[1:]")
    window = src[idx:idx + 5000]
    assert "all_room_responses.append(room_resp)" in window
    assert "room_map = resolve_room_provider_codes(all_room_responses)" in window


# ======================================================================
# The error-guidance fix (a real Hotel room error must not suggest a Tour/Ticket Code fix)
# ======================================================================
def test_room_already_exists_error_has_its_own_earlier_matching_guidance():
    src = _read_app_py()
    idx_specific = src.index('"already exists for contract"')
    idx_generic = src.index('("already exists", "code",')
    assert idx_specific < idx_generic, (
        "the specific room-conflict pattern must be listed BEFORE the generic "
        "Tour/Ticket-code pattern, since _publish_error_guidance returns the FIRST match"
    )


def test_room_already_exists_guidance_mentions_rooms_and_explicitly_not_a_tour_ticket_code_issue():
    src = _read_app_py()
    idx = src.index('"already exists for contract"')
    window = src[idx:idx + 400]
    assert "Rooms section" in window
    assert "not a Tour/Ticket" in window
